config/routes.rb
Rails.application.routes.draw do
  # A visitor can see the list of all restaurants.
  # GET "restaurants"
  # A visitor can add a new restaurant, and be redirected to the show view of that new restaurant.
  # GET "restaurants/new"
  # POST "restaurants"
  # A visitor can see the details of a restaurant, with all the reviews related to the restaurant.
  # GET "restaurants/38"
  # A visitor can add a new review to a restaurant
  # GET "restaurants/38/reviews/new"
  # POST "restaurants/38/reviews"
  root to: 'restaurants#index'

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  self.table_name = "yelp_restaurants"
  has_many :reviews, dependent: :destroy, foreign_key: "yelp_restaurant_id"

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  self.table_name = "yelp_reviews"
  belongs_to :restaurant, foreign_key: "yelp_restaurant_id"

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @categories = ["chinese", "italian", "japanese", "french", "belgian"]
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark mb-4">
    <%= link_to 'Restaurants', restaurants_path, class: "navbar-brand" %>
    <%= link_to 'Create a Restaurant', new_restaurant_path, class: 'nav-item nav-link' %>
    </nav>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<ul>
<% @restaurants.each do |restaurant|%>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create a Restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category, collection: @categories %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Details for <%= @restaurant.name %></h1>

<div class='my-4'>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
</div>

<h1>Leave a Review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>
<% end %>

<% if @restaurant.reviews.count >= 1 %>
<h2>All Reviews</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.rating %>
      <%= review.content %>
    </li>
    <% end %>
</ul>
<% end %>